# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acf05af29b374f8dc11ba411f074db83b6fae31ed9e41c92dd703855db040fb367adace7028bace806b9c6d59c1e57acce7e230587ddd826f29bfde753ed59c5

test:
  secret_key_base: f99a0f2d993c613344bcfdb71e3ea80d088a78dc37a4be25d4c7b2dc3944d2e0602fc0bba0195e364729fe0a4a41ca814c2db93be8296c4a30d8d87755218a52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
